/**
 * Scraped Data Flow Integration Test
 *
 * Verifies:
 * 1. Email personalizer injects enriched scraped data (rating, reviews, address, category)
 * 2. Notes parsing helpers extract fields from scraper output format
 * 3. Lead validator correctly handles enriched scraped leads
 * 4. End-to-end: mock scrape → validation → email personalization → correct output
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  injectLeadData,
  extractRatingFromNotes,
  extractReviewsFromNotes,
  extractAddressFromNotes,
  extractCategoryFromNotes,
  getLeadContext,
} from "../email-personalizer";
import { validateAndFilterLeads, computeScrapedLeadScore } from "../lead-validator";
import type { Lead, ScrapedLead } from "../types";

// ========================================================================
// MOCK SETUP
// ========================================================================

vi.mock("@/lib/email/email-sender", () => ({
  sendEmail: vi.fn().mockResolvedValue({ success: true, messageId: "mock-email-id" }),
  buildNurtureEmail: vi.fn().mockImplementation(({ leadName, step }: any) => ({
    subject: step?.subject || `Hello ${leadName}!`,
    html: `<p>${step?.template || "Welcome!"}</p>`,
    text: step?.template || "Welcome!",
  })),
  buildAppointmentEmail: vi.fn().mockResolvedValue({ subject: "Appt", html: "<p>Confirmed</p>", text: "Confirmed" }),
}));

vi.mock("@/lib/whatsapp/whatsapp-web", () => ({
  sendWhatsAppMessage: vi.fn().mockResolvedValue({ success: true }),
  isWhatsAppConnected: vi.fn().mockResolvedValue(true),
}));

// In-memory stores
const leadStore = new Map<string, Lead>();
const sequenceStore = new Map<string, any>();
const sequenceByLeadStore = new Map<string, string[]>();
const settingStore = new Map<string, string>();

vi.mock("@/lib/db", async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...(actual as object),
    getSetting: vi.fn(async (key: string) => settingStore.get(key)),
    setSetting: vi.fn(async (key: string, value: string) => { settingStore.set(key, value); }),
    dbList: vi.fn(async (table: string) => {
      if (table === "leads") return Array.from(leadStore.values());
      return [];
    }),
    dbCount: vi.fn(async (table: string) => {
      if (table === "leads") return leadStore.size;
      return 0;
    }),
    dbGet: vi.fn(async (_table: string, id: string) => leadStore.get(id) || null),
    dbUpdate: vi.fn(async (_table: string, id: string, updates: any) => {
      const existing = leadStore.get(id);
      if (!existing) return null;
      const updated = { ...existing, ...updates };
      leadStore.set(id, updated);
      return updated;
    }),
    upsertLead: vi.fn(async (lead: Lead) => { leadStore.set(lead.id, lead); return lead; }),
    upsertAppointment: vi.fn(async (apt: any) => apt),
    upsertResult: vi.fn().mockResolvedValue(undefined),
    getRecentResults: vi.fn().mockResolvedValue([]),
    saveSequence: vi.fn(async (seq: any) => {
      sequenceStore.set(seq.id, { ...seq, startedAt: new Date(seq.startedAt) });
      const existing = sequenceByLeadStore.get(seq.leadId) || [];
      if (!existing.includes(seq.id)) {
        sequenceByLeadStore.set(seq.leadId, [...existing, seq.id]);
      }
    }),
    loadSequence: vi.fn(async (id: string) => {
      const seq = sequenceStore.get(id);
      return seq ? { ...seq, startedAt: new Date(seq.startedAt) } : null;
    }),
    loadSequencesByLead: vi.fn(async (leadId: string) => {
      return sequenceByLeadStore.get(leadId) || [];
    }),
    loadAllSequenceIds: vi.fn(async () => Array.from(sequenceStore.keys())),
    countActiveSequences: vi.fn(async () => {
      return Array.from(sequenceStore.values()).filter((s: any) => s.status === "active").length;
    }),
  };
});

beforeEach(() => {
  vi.clearAllMocks();
  leadStore.clear();
  sequenceStore.clear();
  sequenceByLeadStore.clear();
  settingStore.clear();
});

// ========================================================================
// HELPERS — Create leads with enriched scraped data
// ========================================================================

/**
 * Mock the format of notes generated by google-maps-scraper's buildNotes().
 * The enriched data (rating, reviews, address, category) is stored within
 * the notes string, and extracted by the parsing helpers in email-personalizer.ts.
 */
const MOCK_NOTES_FULL =
  'Google Maps lead — "wellness center portland". | 4.5★ (127 reviews) | Category: Wellness Center | Located at: 123 Main Street, Portland, OR | Phone: +1 (555) 123-4567 | Web: https://harmonywellness.com';

const MOCK_NOTES_MINIMAL =
  'Google Maps lead — "yoga studio". | 3.8★ (42 reviews) | Category: Yoga Studio';

const MOCK_NOTES_EMPTY = 'Google Maps lead — "search query".';

function createScrapedLead(overrides: Partial<ScrapedLead> = {}): ScrapedLead {
  return {
    name: "Harmony Wellness Center",
    company: "Harmony Wellness Center",
    role: "Wellness Center",
    source: "google-maps",
    sourceUrl: "https://harmonywellness.com",
    score: 75,
    personaType: "wellness-seeker",
    email: "info@harmonywellness.com",
    phone: "+1 (555) 123-4567",
    rating: "4.5",
    reviews: "127",
    address: "123 Main Street, Portland, OR",
    category: "Wellness Center",
    businessDetails:
      "4.5★ (127 reviews) | Category: Wellness Center | Located at: 123 Main Street, Portland, OR | Phone: +1 (555) 123-4567 | Website: https://harmonywellness.com",
    notes: MOCK_NOTES_FULL,
    ...overrides,
  };
}

function createLead(overrides: Partial<Lead> = {}): Lead {
  return {
    id: crypto.randomUUID(),
    name: "Harmony Wellness Center",
    company: "Harmony Wellness Center",
    role: "Wellness Center",
    email: "info@harmonywellness.com",
    phone: "+1 (555) 123-4567",
    source: "google-maps",
    sourceUrl: "https://harmonywellness.com",
    status: "new",
    pipelineStage: "sourced",
    score: 75,
    personaType: "wellness-seeker",
    notes: MOCK_NOTES_FULL,
    createdAt: new Date(),
    ...overrides,
  };
}

// ========================================================================
// TEST 1: Notes Parsing — Extract fields from scraper's notes format
// ========================================================================

describe("Notes parsing helpers (from scraper output)", () => {
  it("extracts rating from full notes", () => {
    expect(extractRatingFromNotes(MOCK_NOTES_FULL)).toBe("4.5");
    expect(extractRatingFromNotes("")).toBe("");
    expect(extractRatingFromNotes("No rating here")).toBe("");
  });

  it("extracts reviews count from notes", () => {
    expect(extractReviewsFromNotes(MOCK_NOTES_FULL)).toBe("127");
    expect(extractReviewsFromNotes("4.5★")).toBe("");
    expect(extractReviewsFromNotes("3.9★ (42 reviews)")).toBe("42");
    // Multiple-word review count
    expect(extractReviewsFromNotes("4.5★ (1,234 reviews)")).toBe("1234");
  });

  it("extracts address from notes", () => {
    expect(extractAddressFromNotes(MOCK_NOTES_FULL)).toBe("123 Main Street, Portland, OR");
    expect(extractAddressFromNotes(MOCK_NOTES_MINIMAL)).toBe("");
    expect(extractAddressFromNotes("No address")).toBe("");
  });

  it("extracts category from notes", () => {
    expect(extractCategoryFromNotes(MOCK_NOTES_FULL)).toBe("Wellness Center");
    expect(extractCategoryFromNotes(MOCK_NOTES_MINIMAL)).toBe("Yoga Studio");
    expect(extractCategoryFromNotes("No category")).toBe("");
  });

  it("extracts fields from minimal notes", () => {
    expect(extractRatingFromNotes(MOCK_NOTES_MINIMAL)).toBe("3.8");
    expect(extractReviewsFromNotes(MOCK_NOTES_MINIMAL)).toBe("42");
    expect(extractCategoryFromNotes(MOCK_NOTES_MINIMAL)).toBe("Yoga Studio");
    expect(extractAddressFromNotes(MOCK_NOTES_MINIMAL)).toBe("");
  });

  it("returns empty strings when no scraped data in notes", () => {
    expect(extractRatingFromNotes(MOCK_NOTES_EMPTY)).toBe("");
    expect(extractReviewsFromNotes(MOCK_NOTES_EMPTY)).toBe("");
    expect(extractAddressFromNotes(MOCK_NOTES_EMPTY)).toBe("");
    expect(extractCategoryFromNotes(MOCK_NOTES_EMPTY)).toBe("");
  });

  it("extracts from realistic multi-city scraper format", () => {
    const nyNotes =
      'Google Maps lead — "wellness center new york". | 4.2★ (89 reviews) | Category: Medical Practice | Located at: 456 Oak Avenue, New York, NY | Phone: +1 (212) 555-8901 | Web: https://drsmithwellness.com';
    expect(extractRatingFromNotes(nyNotes)).toBe("4.2");
    expect(extractReviewsFromNotes(nyNotes)).toBe("89");
    expect(extractAddressFromNotes(nyNotes)).toBe("456 Oak Avenue, New York, NY");
    expect(extractCategoryFromNotes(nyNotes)).toBe("Medical Practice");
  });
});

// ========================================================================
// TEST 2: Email Personalizer — Inject scraped data into templates
// ========================================================================

describe("Email personalizer with enriched scraped data", () => {
  it("injects {company} placeholder from lead company name", () => {
    const lead = createLead();
    const result = injectLeadData("I came across {company} and was impressed!", lead);
    expect(result).toBe("I came across Harmony Wellness Center and was impressed!");
  });

  it("injects {category} placeholder from parsed notes", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    const result = injectLeadData("As a fellow {category}, I wanted to reach out.", lead);
    expect(result).toBe("As a fellow Wellness Center, I wanted to reach out.");
  });

  it("injects {rating} and {reviews} placeholders from parsed notes", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    const result = injectLeadData("Your {rating}★ rating with {reviews} reviews is impressive!", lead);
    expect(result).toBe("Your 4.5★ rating with 127 reviews is impressive!");
  });

  it("injects {address} placeholder from parsed notes", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    const result = injectLeadData("Located at {address}.", lead);
    expect(result).toBe("Located at 123 Main Street, Portland, OR.");
  });

  it("injects {website} placeholder from sourceUrl", () => {
    const lead = createLead({ sourceUrl: "https://harmonywellness.com" });
    const result = injectLeadData("Visit {website}.", lead);
    expect(result).toBe("Visit https://harmonywellness.com.");
  });

  it("injects all placeholders in a realistic template and removes all template braces", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    const template =
      "Hi there,\n\nI came across {company} — a {category} — and was impressed by your {rating}★ rating across {reviews} reviews.\n\nLocated at {address}, you're in a great area for what we do.";
    const result = injectLeadData(template, lead);
    expect(result).toContain("Harmony Wellness Center");
    expect(result).toContain("Wellness Center");
    expect(result).toContain("4.5");
    expect(result).toContain("127");
    expect(result).toContain("123 Main Street, Portland, OR");
    expect(result).not.toContain("{company}");
    expect(result).not.toContain("{category}");
    expect(result).not.toContain("{rating}");
    expect(result).not.toContain("{reviews}");
    expect(result).not.toContain("{address}");
  });

  it("gracefully removes missing placeholders when no scraped data in notes", () => {
    const lead = createLead({ notes: MOCK_NOTES_EMPTY });
    const template =
      "Hi {company}, your {category} ({rating}★, {reviews} reviews) at {address} looks great!";
    const result = injectLeadData(template, lead);
    // Company should still be present (from lead.company field)
    expect(result).toContain("Harmony Wellness Center");
    // Missing parsed fields should be cleaned up
    expect(result).not.toContain("{company}");
    expect(result).not.toContain("{category}");
    expect(result).not.toContain("{rating}");
    expect(result).not.toContain("{reviews}");
    expect(result).not.toContain("{address}");
    // No double spaces or trailing commas from removed placeholders
    expect(result).not.toContain("  ");
  });

  it("handles empty notes gracefully", () => {
    const lead = createLead({ notes: "" });
    const result = injectLeadData("Hello {company}!", lead);
    expect(result).toBe("Hello Harmony Wellness Center!");
  });

  it("handles {businessDetails} placeholder with full notes string", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    const result = injectLeadData("Details: {businessDetails}", lead);
    expect(result).toContain("4.5★");
    expect(result).toContain("127 reviews");
    expect(result).toContain("Wellness Center");
    expect(result).not.toContain("{businessDetails}");
  });

  it("handles {score} placeholder", () => {
    const lead = createLead({ score: 82 });
    const result = injectLeadData("Lead score: {score}", lead);
    expect(result).toBe("Lead score: 82");
  });

  it("injects a real Healy Email 1 template correctly", () => {
    const lead = createLead({ notes: MOCK_NOTES_FULL });
    // This is a simplified version of the real wellness-seeker Email 1
    const healyTemplate = `Hi {name},

I hope this email finds you well! My name is Sarah from Healy, and I came across {company} while browsing wellness-focused businesses. I was impressed by what you're building.

As a {category}, I thought you might be interested in frequency technology.

Would you be open to a brief conversation?`;

    const result = injectLeadData(healyTemplate, lead);
    // Company name injected
    expect(result).toContain("Harmony Wellness Center");
    // Category injected
    expect(result).toContain("Wellness Center");
    // No raw placeholders
    expect(result).not.toContain("{company}");
    expect(result).not.toContain("{category}");
    // {name} is intentionally not replaced (done separately by nurture engine)
    expect(result).toContain("{name}");
  });
});

// ========================================================================
// TEST 3: getLeadContext — Extracts scraped data from lead fields
// ========================================================================

describe("getLeadContext", () => {
  it("extracts company from lead.company field", () => {
    const ctx = getLeadContext(createLead({ notes: MOCK_NOTES_FULL }));
    expect(ctx.company).toBe("Harmony Wellness Center");
  });

  it("falls back company to lead.name if company is empty", () => {
    const ctx = getLeadContext(createLead({ company: "", notes: MOCK_NOTES_FULL }));
    expect(ctx.company).toBe("Harmony Wellness Center");
  });

  it("extracts category from notes", () => {
    const ctx = getLeadContext(createLead({ notes: MOCK_NOTES_FULL }));
    expect(ctx.category).toBe("Wellness Center");
  });

  it("extracts rating from notes", () => {
    const ctx = getLeadContext(createLead({ notes: MOCK_NOTES_FULL }));
    expect(ctx.rating).toBe("4.5");
  });

  it("extracts reviews from notes", () => {
    const ctx = getLeadContext(createLead({ notes: MOCK_NOTES_FULL }));
    expect(ctx.reviews).toBe("127");
  });

  it("uses sourceUrl for website", () => {
    const ctx = getLeadContext(createLead({ sourceUrl: "https://example.com" }));
    expect(ctx.website).toBe("https://example.com");
  });

  it("returns empty category when notes have no scraper data", () => {
    const ctx = getLeadContext(createLead({ notes: MOCK_NOTES_EMPTY }));
    expect(ctx.category).toBe("");
    expect(ctx.rating).toBe("");
    expect(ctx.reviews).toBe("");
    expect(ctx.address).toBe("");
  });
});

// ========================================================================
// TEST 4: Lead Validator — Handles enriched data correctly
// ========================================================================

describe("Lead validator with enriched scraped data", () => {
  it("passes fully enriched leads with email and phone", () => {
    const lead = createScrapedLead();
    const { validLeads, summary } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(1);
    expect(summary.skippedLeads).toBe(0);
    expect(summary.validLeads).toBe(1);
  });

  it("passes leads with only email (no phone)", () => {
    const lead = createScrapedLead({ phone: "" });
    const { validLeads } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(1);
  });

  it("passes leads with only phone (no email)", () => {
    const lead = createScrapedLead({ email: "" });
    const { validLeads } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(1);
  });

  it("skips leads with both email and phone blank", () => {
    const lead = createScrapedLead({ email: "", phone: "" });
    const { validLeads, summary } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(0);
    expect(summary.skippedLeads).toBe(1);
    expect(summary.skippedReasons["No email or phone — unreachable"]).toBe(1);
  });

  it("skips leads with invalid email format", () => {
    const lead = createScrapedLead({ email: "not-an-email" });
    const { validLeads } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(0);
  });

  it("allows info@, hello@, contact@, support@ emails (legitimate business emails)", () => {
    for (const email of [
      "info@balancehealth.com",
      "hello@wellness.com",
      "contact@clinic.com",
      "support@studio.com",
    ]) {
      const lead = createScrapedLead({ email });
      const { validLeads } = validateAndFilterLeads([lead]);
      expect(validLeads).toHaveLength(1);
    }
  });

  it("skips noreply@ and example@ emails (non-deliverable)", () => {
    for (const email of ["noreply@company.com", "no-reply@test.com", "example@domain.com"]) {
      const lead = createScrapedLead({ email });
      const { validLeads } = validateAndFilterLeads([lead]);
      expect(validLeads).toHaveLength(0);
    }
  });

  it("skips leads with empty/invalid business name", () => {
    const lead = createScrapedLead({ name: "" });
    const { validLeads } = validateAndFilterLeads([lead]);
    expect(validLeads).toHaveLength(0);
  });

  it("validates a mixed batch and returns correct counts", () => {
    const leads = [
      createScrapedLead({ name: "Good Lead 1", email: "info@good1.com" }),
      createScrapedLead({ name: "Good Lead 2", email: "hello@good2.com", phone: "" }),
      createScrapedLead({ name: "", email: "info@bad.com" }),             // no name
      createScrapedLead({ email: "", phone: "" }),                        // no contact
      createScrapedLead({ email: "noreply@bad.com" }),                    // non-deliverable
    ];
    const { validLeads, skippedLeads, summary } = validateAndFilterLeads(leads);
    expect(validLeads).toHaveLength(2);
    expect(skippedLeads).toHaveLength(3);
    expect(summary.validLeads).toBe(2);
    expect(summary.skippedLeads).toBe(3);
    expect(summary.totalLeads).toBe(5);
  });
});

// ========================================================================
// TEST 5: computeScrapedLeadScore — Uses enriched fields for scoring
// ========================================================================

describe("computeScrapedLeadScore with enriched data", () => {
  it("computes max score (100) for fully enriched leads", () => {
    const lead = createScrapedLead();
    const score = computeScrapedLeadScore(lead);
    // 50 base + 15 email + 10 phone + 13.5 rating(4.5*3) + 10 reviews>50 + 5 website + 3 address + 2 category = 108.5 → capped at 100
    expect(score).toBe(100);
  });

  it("computes correct intermediate score for leads with some data", () => {
    const lead = createScrapedLead({
      email: "test@example.com",
      phone: "",
      rating: "3.5",
      reviews: "20",
      sourceUrl: "",
      address: "",
      category: "",
    });
    const score = computeScrapedLeadScore(lead);
    // 50 base + 15 email + 10.5 rating(3.5*3 → 11) + 0 reviews(20 < 50 threshold) = 76
    expect(score).toBe(76);
  });

  it("computes base score for leads with no enriched fields", () => {
    const lead = createScrapedLead({
      email: "",
      phone: "",
      rating: "",
      reviews: "",
      sourceUrl: "",
      address: "",
      category: "",
    });
    const score = computeScrapedLeadScore(lead);
    expect(score).toBe(50);
  });
});

// ========================================================================
// TEST 6: Realistic scraper output format — Simulate buildNotes() output
// ========================================================================

describe("Scraper notes format compatibility", () => {
  // These test the exact format produced by google-maps-scraper's buildNotes()
  // to ensure the parsing helpers can extract data from real scraper output.

  it("parses notes with all fields present", () => {
    const notes = 'Google Maps lead — "wellness center". | 4.8★ (256 reviews) | Category: Health & Wellness | Located at: 789 Pine Road, Austin, TX | Phone: +1 (512) 555-1234 | Web: https://example.com';
    expect(extractRatingFromNotes(notes)).toBe("4.8");
    expect(extractReviewsFromNotes(notes)).toBe("256");
    expect(extractAddressFromNotes(notes)).toBe("789 Pine Road, Austin, TX");
    expect(extractCategoryFromNotes(notes)).toBe("Health & Wellness");
  });

  it("parses notes with missing optional fields", () => {
    const notes = 'Google Maps lead — "search query". | 3.0★ | Category: Salon';
    expect(extractRatingFromNotes(notes)).toBe("3.0");
    expect(extractReviewsFromNotes(notes)).toBe("");
    expect(extractAddressFromNotes(notes)).toBe("");
    expect(extractCategoryFromNotes(notes)).toBe("Salon");
  });

  it("parses notes with only name and source (no enriched data)", () => {
    const notes = 'Google Maps lead — "test".';
    expect(extractRatingFromNotes(notes)).toBe("");
    expect(extractReviewsFromNotes(notes)).toBe("");
    expect(extractAddressFromNotes(notes)).toBe("");
    expect(extractCategoryFromNotes(notes)).toBe("");
  });

  it("parses notes from 1-5 star range", () => {
    for (const rating of ["1.0", "2.3", "3.5", "4.9", "5.0"]) {
      const notes = `Google Maps lead. | ${rating}★ (10 reviews) | Category: Test`;
      expect(extractRatingFromNotes(notes)).toBe(rating);
    }
  });
});
